export type ActionSitysType =
  'ADD_SITY' | 'ADD_SITY_SAGA'| 'DOUNLOAD_SITY'
   |'DOUNLOAD_SITY_SAGA'|'DELETE_SITY_SAGA'|'DELETE_SITY'
   |'POISK_SITY' | 'POISK_SITY_SAGA'|'DROP_SITY'|'DROP_SITY_SAGA'|'START_DROG'|'START_DROG_SAGA';
